name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
jobs:
  build:
    name: build from matrix
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest,self-hosted]
      runs-on: ${{ matrix.os }}
      env:
        app_name: Product_${{ matrix.os }}.jar
        java_setup: actions/setup-java@v1.4.4
      steps:
        - name: build
          uses: ${{ java_setup }}
          run: javac src/Main.java 

        - name: create jar
          uses: ${{ java_setup }}
          run: jar cmvf manifest.mf ${{ env.app_name }} * && java -jar ${{ env.app_name }}


  
  
