name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
jobs:
  build:
    name: build from matrix
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest,self-hosted]
      runs-on: ${{ matrix.os }}
  
  
