name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
env:
  PATH_TO_MAIN_FILE: src/Main.java 
  PATH_TO_MANIFEST_FILE: manifest.mf
  ARTIFACT_FILE_NAME: Product_*.jar


jobs:
  check_style:
    name: Check style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Run java checkstyle
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true
      - name: Print diffs
        run: git --no-pager diff 

  build:
    name: Build
    needs: check_style
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      app_name: Product_${{ matrix.os }}.jar
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build
        run: javac $PATH_TO_MAIN_FILE

      - name: Create jar
        run: jar cmvf $PATH_TO_MANIFEST_FILE ${{ env.app_name }} * 

        uses: actions/upload-artifact@v3.1.2
        with:
          name: Product
          path: ${{ env.app_name }}
          retention-days: 1

  send_artifacts:
    name: Send artifacts to Google Drive
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: Product

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
            credentials: ${{ secrets.GOOGLE_CLIENT_API }}
            filename: $ARTIFACT_FILE_NAME
            folderId: ${{ secrets.FOLDER_ID }}
            overwrite: "true" 


